#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the climbingLeaderboard function below.
def climbingLeaderboard(scores, alice):
    ranks =[]
    for i in alice:
        rank = 1
        prevRank = scores[0]
        players = len(scores)
        for j in scores:
            players -= 1
            if i > j and j != prevRank:
                ranks.append(rank+1)
                break
            elif i > j and j == prevRank:
                ranks.append(rank)
                break
            elif i < j and prevRank != j:
                rank += 1
                prevRank = j
            if players ==0:
                ranks.append(rank+1)
    print(ranks)
    return ranks
if __name__ == '__main__':
    scores_count = int(input())

    scores = list(map(int, input().rstrip().split()))

    alice_count = int(input())

    alice = list(map(int, input().rstrip().split()))

    result = climbingLeaderboard(scores, alice)
